[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/staff-centre/sales"
  to = "/staff-centre/crm"
  status = 301

[[redirects]]
  from = "/:module/sales"
  to = "/staff-centre/crm"
  status = 301

[[redirects]]
  from = "/"
  to = "/login"
  status = 302

[[redirects]]
  from = "/index.html"
  to = "/login"
  status = 302

[[redirects]]
  from = "/opero.html"
  to = "/login"
  status = 301

[[redirects]]
  from = "/landing.html"
  to = "/login"
  status = 301
