-- OPERO OWNER PORTAL: Run this in Supabase SQL Editor
-- Project: mzjsxrlgnthelwwtfkke

-- 1. Owner profiles table
-- Links an Opero user account (owner login) to their specific properties
CREATE TABLE IF NOT EXISTS owner_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT,
  email TEXT,
  phone TEXT,
  property_ids UUID[] DEFAULT '{}', -- array of property IDs this owner has access to
  split_percentage NUMERIC DEFAULT 80, -- owner's cut (e.g. 80 = 80%, we keep 20%)
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast lookup by user_id on login
CREATE INDEX IF NOT EXISTS owner_profiles_user_id_idx ON owner_profiles(user_id);

-- 2. Owner statements table
-- Monthly statements generated by staff for each owner
CREATE TABLE IF NOT EXISTS owner_statements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID REFERENCES owner_profiles(id) ON DELETE CASCADE,
  property_id UUID REFERENCES properties(id) ON DELETE SET NULL,
  property_name TEXT,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  gross_revenue NUMERIC DEFAULT 0,
  management_fee NUMERIC DEFAULT 0,
  expenses NUMERIC DEFAULT 0,
  owner_amount NUMERIC DEFAULT 0,
  notes TEXT,
  status TEXT DEFAULT 'draft', -- 'draft' | 'sent' | 'paid'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for owner lookup
CREATE INDEX IF NOT EXISTS owner_statements_owner_id_idx ON owner_statements(owner_id);

-- 3. Enable Row Level Security
ALTER TABLE owner_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE owner_statements ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
-- Owners can only see their own profile
CREATE POLICY "Owners see own profile"
  ON owner_profiles FOR SELECT
  USING (auth.uid() = user_id);

-- Owners can only see their own statements
CREATE POLICY "Owners see own statements"
  ON owner_statements FOR SELECT
  USING (
    owner_id IN (
      SELECT id FROM owner_profiles WHERE user_id = auth.uid()
    )
  );

-- Staff (authenticated users who are NOT owners) can see and manage all owner profiles
-- (This relies on your existing staff auth setup - adjust if you use a separate admin check)
CREATE POLICY "Staff full access to owner_profiles"
  ON owner_profiles FOR ALL
  USING (
    auth.uid() NOT IN (SELECT user_id FROM owner_profiles)
    OR auth.uid() = user_id
  );

CREATE POLICY "Staff full access to owner_statements"
  ON owner_statements FOR ALL
  USING (true); -- restrict further if needed

-- 5. How to create an owner account:
-- Step 1: Create a user in Supabase Auth (Authentication > Users > Invite user)
--         with the owner's email and a temporary password
-- Step 2: Note the new user's UUID from the users table
-- Step 3: Run this insert to link them to their properties:
--
-- INSERT INTO owner_profiles (user_id, name, email, property_ids, split_percentage)
-- VALUES (
--   'OWNER-USER-UUID-HERE',
--   'Khrishawn Powell',                    -- owner name
--   'khrishawn@example.com',              -- owner email
--   ARRAY['PROPERTY-UUID-1', 'PROPERTY-UUID-2']::UUID[], -- their property IDs
--   80                                     -- 80% owner share (20% your fee)
-- );
